spring:
  application:
    name: aliyun-oss-front
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: http://10.211.55.34:8848

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9300/oauth/token
      user-authorization-uri: http://localhost:9300/oauth/authorize
    resource:
      token-info-uri: http://localhost:9300/oauth/check_token
server:
  # ${random.int[9000,9999]} 随机端口
  port: 10002
management:
  endpoints:
    web:
      exposure:
        include: "*"